application:
  port: 8080
database:
  host: "localhost"
  port: 5432
  username: "app"
  password: "secret"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@example.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000